apiVersion: v1
kind: ServiceAccount
metadata:
  name: swaggies-sa
  namespace: swaggies
  annotations:
    iam.gke.io/gcp-service-account: swaggies-sa@swaggies-escrow.iam.gserviceaccount.com

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: swaggies-escrow
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: swaggies-cluster
          serviceAccountRef:
            name: swaggies-sa
            namespace: swaggies

---
# Auth Service Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: swaggies
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: swaggies-jwt-secret
    - secretKey: REFRESH_TOKEN_SECRET
      remoteRef:
        key: swaggies-refresh-token-secret
    - secretKey: MONGO_URI
      remoteRef:
        key: swaggies-auth-mongo-uri
    - secretKey: MAILTRAP_TOKEN
      remoteRef:
        key: swaggies-mailtrap-token
    - secretKey: RESEND_TOKEN
      remoteRef:
        key: swaggies-resend-token
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: swaggies-encryption-key
---
# User Service Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-secrets
  namespace: swaggies
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: user-service-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: swaggies-jwt-secret
    - secretKey: MONGO_URI
      remoteRef:
        key: swaggies-user-mongo-uri

---
# Wallet Service Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallet-service-secrets
  namespace: swaggies
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: wallet-service-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: swaggies-jwt-secret
    - secretKey: MONGO_URI
      remoteRef:
        key: swaggies-wallet-mongo-uri
    - secretKey: MONNIFY_API_KEY
      remoteRef:
        key: swaggies-monnify-api-key
    - secretKey: MONNIFY_SECRET_KEY
      remoteRef:
        key: swaggies-monnify-secret-key
    - secretKey: MONNIFY_CONTRACT_CODE
      remoteRef:
        key: swaggies-monnify-contract-code
    - secretKey: EXCHANGE_RATE_API_KEY
      remoteRef:
        key: swaggies-exchange-rate-api-key
    - secretKey: FLW_SEC_TEST_KEY
      remoteRef:
        key: swaggies-flw-sec-test-key
    - secretKey: FLW_PUB_KEY
      remoteRef:
        key: swaggies-flw-pub-key
    - secretKey: FLW_ENC_KEY
      remoteRef:
        key: swaggies-flw-enc-key
    - secretKey: FLW_SEC_LIVE_KEY
      remoteRef:
        key: swaggies-flw-sec-live-key
    - secretKey: FLW_PUB_LIVE_KEY
      remoteRef:
        key: swaggies-flw-pub-live-key
    - secretKey: FLW_ENC_LIVE_KEY
      remoteRef:
        key: swaggies-flw-enc-live-key
    - secretKey: FLW_SECRET_HASH
      remoteRef:
        key: swaggies-flw-secret-hash

---
# Payment Service Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-service-secrets
  namespace: swaggies
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: payment-service-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: swaggies-jwt-secret
    - secretKey: MONGO_URI
      remoteRef:
        key: swaggies-payment-mongo-uri
    - secretKey: PAYSTACK_SECRET_KEY
      remoteRef:
        key: swaggies-paystack-secret-key

---
# Gateway Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-secrets
  namespace: swaggies
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: gateway-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: swaggies-jwt-secret

---
# Budget Service Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: budget-service-secrets
  namespace: swaggies
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: budget-service-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: swaggies-jwt-secret
    - secretKey: MONGO_URI
      remoteRef:
        key: swaggies-budget-mongo-uri

---
# Notification Service Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-service-secrets
  namespace: swaggies
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: notification-service-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: swaggies-jwt-secret
    - secretKey: MAILTRAP_TOKEN
      remoteRef:
        key: swaggies-mailtrap-token
    - secretKey: RESEND_TOKEN
      remoteRef:
        key: swaggies-resend-token
    - secretKey: RESEND_MAIL
      remoteRef:
        key: swaggies-resend-mail
    - secretKey: GMAIL_USER
      remoteRef:
        key: swaggies-gmail-user
    - secretKey: GMAIL_APP_PASSWORD
      remoteRef:
        key: swaggies-gmail-app-password
